### ISSUE TITLE
Cannot read property 'clientId' of undefined

### ISSUE THREAD

**Issue by shnathoskhan** [actions-on-google/dialogflow-iosched-nodejs#1]
Hlo, 

pls, hlp me to fix this year.

Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'clientId' of undefined
    at Object.<anonymous> (F:\Demos\Android-Studio\aogdin\functions\app.js:45:20)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\Demos\Android-Studio\aogdin\functions\index.js:15:15)
    at Module._compile (module.js:660:30)

**Comment by shnathoskhan** [comment]
> Hlo,
> 
> pls, hlp me to fix this year.
> 
> Error: Error occurred while parsing your function triggers.
> 
> TypeError: Cannot read property 'clientId' of undefined
> at Object. (F:\Demos\Android-Studio\aogdin\functions\app.js:45:20)
> at Module._compile (module.js:660:30)
> at Object.Module._extensions..js (module.js:671:10)
> at Module.load (module.js:573:32)
> at tryModuleLoad (module.js:513:12)
> at Function.Module._load (module.js:505:3)
> at Module.require (module.js:604:17)
> at require (internal/module.js:11:18)
> at Object. (F:\Demos\Android-Studio\aogdin\functions\index.js:15:15)
> at Module._compile (module.js:660:30)

hlo..? any one. hlp me.

**Comment by findzaatar** [comment]
Sample updated with latest fix.
